### ISSUE TITLE
dash/components/dash-core-components/. failed to set up 

### ISSUE THREAD

**Issue by loveJasmine** [plotly/dash#2166]
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                 0.42.0
dash-core-components 0.47.0
dash-html-components 0.16.0
dash-renderer        0.23.0
dash-table           3.6.0
```
-  if frontend related, tell us your Browser, Version and OS

**Describe the bug**

**Expected behavior**

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

**Comment by alexcjohnson** [comment]
@loveJasmine I'm not sure what "failed to set up" means, can you say more?

**Comment by loveJasmine** [comment]
https://github.com/plotly/dash/tree/dev/components/dash-core-components


it doesn't work!!!
we can see a label with failed!

**Comment by alexcjohnson** [comment]
Ah I see - I think that readme was just never changed when we merged dash-core-components into the main dash repo. It doesn’t have its own CI tests anymore, so we should just remove that badge (and probably other edits to that readme). Thanks for pointing this out.

**Comment by loveJasmine** [comment]
https://github.com/plotly/dash/issues/2117

but I followed the steps in https://github.com/plotly/dash/blob/dev/CONTRIBUTING.md
still fails

https://github.com/plotly/dash/issues/2117
