### ISSUE TITLE
[BUG] search_value triggers unrelated callbacks, making dropdown search unusable

### ISSUE THREAD

**Issue by oegedijk** [plotly/dash#2428]
While chasing down a bug in explainerdashboard, I noticed that when you have a dynamic server side dropdown search, and also have a callback targeting dropdown.value, then this latter gets triggered everytime you search in the dropdown. Usually with unwanted side effects. **In this case it makes the dropdown search completely unusable.** 

Below an example, with a dropdown, and a select random item button. Searching in the dropdown triggers the button callback. Including a callback.context check to see if the button callback was indeed triggered by the button n_clicks input seems to fix the problem.

```python
import random
import dash
from dash import Dash, dcc, html, dcc, Input, Output, State
from dash.exceptions import PreventUpdate

options = [str(i) for i in range(1000)]

app = Dash(__name__)
app.layout = html.Div([
    html.Div(id='dropdown-output'),
    html.Button("Random Button", id='button'),
    dcc.Checklist(options=['fix bug'], value=[], id='fix-bug'),
    dcc.Dropdown(id="index-dropdown", value="654")   
])
    
@app.callback(
    Output("index-dropdown", "value"),
    Input("button", "n_clicks"),
    State('fix-bug', 'value'),
)
def random_index(n_clicks, fix_bug):
    print("triggered random click!")
    if fix_bug and dash.callback_context.triggered_id != 'button':
       raise PreventUpdate
    return random.choice(options)

@app.callback(
    Output("index-dropdown", "options"),
    Input("index-dropdown", "search_value")
)
def update_options(search_value):
    if not search_value:
        raise PreventUpdate
    return [o for o in options if str(search_value) in o]

@app.callback(
    Output("dropdown-output", "children"),
    Input("index-dropdown", "value")
)
def send_output(index):
    return f"selected {index}!"

app.run_server(port=8051, debug=False)
```

**Comment by T4rk1n** [comment]
Duplicate of #2411

**Comment by T4rk1n** [comment]
Fixed along with #2411

**Comment by sergiykhan** [comment]
I have just used an example provided by @oegedijk in Dash 2.9.2 and the problem is still there.

**Comment by bambinobino** [comment]
Same thing here, having the problem still in 2.9.2

**Comment by oegedijk** [comment]
@T4rk1n could we add a failing test for this so that it will get fixed in the next release?

**Comment by bambinobino** [comment]
> @T4rk1n could we add a failing test for this so that it will get fixed in the next release?

I believe this is fixed in Dash v2.10.2

**Comment by sergiykhan** [comment]
Indeed, fixed in 2.10.1
https://github.com/plotly/dash/releases
