### ISSUE TITLE
[BUG] Error loading dependencies

### ISSUE THREAD

**Issue by WWakker** [plotly/dash#2797]
**Describe your context**

```
dash                      2.16.1
dash-bootstrap-components 1.5.0
dash-core-components      2.0.0
dash-daq                  0.5.0
dash-html-components      2.0.0
dash-iconify              0.1.2
dash-mantine-components   0.12.1
dash-table                5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows
    - Browser Chrome

**Describe the bug**

I run this example app:
```python
# Run this app with `python app.py` and
# visit http://127.0.0.1:8050/ in your web browser.


from dash import Dash, dcc, html
import plotly.express as px
import pandas as pd


app = Dash(__name__)

colors = {
    'background': '#111111',
    'text': '#7FDBFF'
}

# assume you have a "long-form" data frame
# see https://plotly.com/python/px-arguments/ for more options
df = pd.DataFrame({
    "Fruit": ["Apples", "Oranges", "Bananas", "Apples", "Oranges", "Bananas"],
    "Amount": [4, 1, 2, 2, 4, 5],
    "City": ["SF", "SF", "SF", "Montreal", "Montreal", "Montreal"]
})

fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")

fig.update_layout(
    plot_bgcolor=colors['background'],
    paper_bgcolor=colors['background'],
    font_color=colors['text']
)

app.layout = html.Div(style={'backgroundColor': colors['background']}, children=[
    html.H1(
        children='Hello Dash',
        style={
            'textAlign': 'center',
            'color': colors['text']
        }
    ),

    html.Div(children='Dash: A web application framework for your data.', style={
        'textAlign': 'center',
        'color': colors['text']
    }),

    dcc.Graph(
        id='example-graph-2',
        figure=fig
    )
])

if __name__ == '__main__':
    app.run(debug=True)
```

On startup, the app loads fine.

When I change something in my code, and the page reloads in the browser, I get the following error:
<img width="562" alt="image" src="https://github.com/plotly/dash/assets/63314097/7187a280-8ebe-4768-8bc1-f74d6fba03df">

If I refresh the browser, the app loads again without problems.

This happens after upgrading my dash version, so could be related to a bug in the later versions.

**Expected behavior**

The page should reload without problems with `debug=True`.

**Screenshots**

See above

**Comment by WWakker** [comment]
Update, when I downgrade to `dash==2.15` it works fine. With `2.16` it fails again.

**Comment by AnnMarieW** [comment]
@WWakker This was fixed in 2.16.1

**Comment by WWakker** [comment]
@AnnMarieW I'm afraid I'm still experiencing the issue with 2.16.1

**Comment by T4rk1n** [comment]
> When I change something in my code, and the page reloads in the browser, I get the following error:

It's a bug with newer version of orjson, dependencies now calls to_json for `running` to set components. When reloading the import on plotly.py seems to fail.
Can uninstall orjson or `import orjson` at the top.

Related to: https://github.com/plotly/plotly.py/issues/3567

**Comment by WWakker** [comment]
> > When I change something in my code, and the page reloads in the browser, I get the following error:
> 
> It's a bug with newer version of orjson, dependencies now calls to_json for `running` to set components. When reloading the import on plotly.py seems to fail. Can uninstall orjson or `import orjson` at the top.
> 
> Related to: [plotly/plotly.py#3567](https://github.com/plotly/plotly.py/issues/3567)

I confirm this, glad that it's not related to Dash

**Comment by Coding-with-Adam** [comment]
Closing this because the issue is in Plotly.py

**Comment by emilykl** [comment]
This issue should be resolved by the next Plotly.py release, now that the above linked PR has been merged.
