### ISSUE TITLE
[BUG] DatePickerRange updatemode not respected

### ISSUE THREAD

**Issue by rzvcs** [plotly/dash#3425]
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

-  replace the result of `pip list | grep dash` below
```
dash                          3.2.0
dash_ag_grid                  31.3.1
dash-bootstrap-components     1.7.1
dash-table                    5.0.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: Windows 11
    - Browser: Chrome
    - Version: 139.0.7258.155

**Describe the bug**

When using dcc.DateRangePicker with updatemode="bothdates" from the UI, selecting the start date waits for the end date selection. However, selecting the end date triggers linked callbacks.

**Expected behavior**

In this updatemode, selecting the end date should wait for selecting the start date.

**Comment by Farkites** [comment]
This issue is fixed with `dash==4.0.0rc3`

**Comment by pierovera** [comment]
I am still seeing this issue with dash 4.1.0. The issue is exactly as described in the original report. I can provide additional info if needed.

**Comment by elklaassen** [comment]
I also still see the issue with dash 4.2.0. I would like to add that after selecting start date, end date is (set to) None and as described before, callback is triggered before selecting end date. This causes my code to crash as I cannot have end date = None. Workarounds like using dcc.Store to preserve the end date value do not work for me.
